### ISSUE TITLE
Local zeebe cluster: connector runtime couldn't connect to platform network

### ISSUE THREAD

**Issue by asys3** [holunda-io/camunda-8-connector-gpt#127]
Hi Bennet,

tried to follow the instructions to start up your example with a local C8 setup ([plain vanilla](https://github.com/camunda/camunda-platform))  but it fails because I couldn't share a common network between the two docker-compose environments (Camunda's and your's named  'connector-network'.

So I tried to reply 1:1 your setup. Did the following:
1. Created connector.secrets.txt from template and uncommented:
ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS=zeebe:26500
CAMUNDA_OPERATE_CLIENT_URL=http://operate:8080
CAMUNDA_OPERATE_CLIENT_USERNAME: demo
CAMUNDA_OPERATE_CLIENT_PASSWORD: demo
ZEEBE_CLIENT_SECURITY_PLAINTEXT=true

2. started up local Zeebe Cluster as instructed with:

> docker compose -f docker-compose.camunda-platform.yml up -d

3. Tried to start connector image as instructed with:
> docker run --env-file connector-secrets.txt holisticon/camunda-8-connector-gpt:develop

Following error occured:

> docker: poorly formatted environment: variable 'CAMUNDA_OPERATE_CLIENT_USERNAME: demo' contains whitespaces.
> See 'docker run --help'.

4. Fixed this typo by removing ' ' before username/pw and tried to restart.
5. Received the following error:
`16:15:11.037 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (zeebe:26500)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host zeebe, cause=java.lang.RuntimeException: java.net.UnknownHostException: zeebe: Name or service not known
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.UnknownHostException: zeebe: Name or service not known
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 5 more
}
16:15:11.055 [grpc-default-executor-0] WARN  io.camunda.zeebe.client.job.poller - Failed to activate jobs for worker gpt-database and job type io.holunda:connector-database:1
io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host zeebe
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)`
	
So 'zeebe' is unknown?!
Could be that I have a problem in my docker setup anywhere?!
Both your docker-compose.camunda-platform.yml and docker-compose.yml refer to the network  'connector-network'.
And therefore I suppose all services, like zeebe, operate, tasklist etc. should be able to be referred from the connector compose file, right?

Had the same problem as described above when trying to use the connector compose file with camunda's default platform compose file.

Any ideas?

Kind regards,
Uwe

**Comment by asys3** [comment]
Simply solved the issue by starting both docker-compose files in the same call:
`docker compose -f docker-compose.camunda-platform.yml -f docker-compose.yml up -d`
So everything works  - even there's no typo with the demo user in connectors-secrets file.
Closing this issue.
Sorry for the confusion.

**Comment by asys3** [comment]
see above

**Comment by Benjoyo** [comment]
Compose now supports profiles, so a single file with an optional platform profile seems to be the cleanest way moving forward. There is a major refactoring to be merged soon anyway, will include that.
